import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopImage from "../components/top-image";
import BottomImage from "../components/bottom-image";
import BottomInfo from "@/components/bottom-info";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`} suppressHydrationWarning={true}>
        <TopImage />
        {children}
        <BottomImage />
        <BottomInfo />
      </body>
    </html>
  );
}
